services:
  hicumes:
    build:
      context: wildfly
      dockerfile: Dockerfile
    image: hicumes.backend
    logging:
      driver: local
      options:
        max-size: 500m
        max-file: 4
    environment:
      #JAVA_TOOL_OPTIONS: "${JAVA_TOOL_OPTIONS} -Dfile.encoding=UTF-8 -Dmp.jwt.verify.publickey.location='http://keycloak:8080/realms/hicumes/protocol/openid-connect/certs' -Dmp.jwt.verify.issuer='http://localhost:8181/realms/hicumes'"
      JAVA_TOOL_OPTIONS: "${JAVA_TOOL_OPTIONS} -Dfile.encoding=UTF-8 -Djboss.bind.address=0.0.0.0"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: http://172.27.40.38:8181/realms/hicumes/protocol/openid-connect/certs
      MP_JWT_VERIFY_ISSUER: http://172.27.40.38:8181/realms/hicumes
      TZ: Europe/Berlin
    container_name: hicumes
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
    - ./AAA_Backend_Logs:/opt/jboss/log
    #  - hicumes-backend-dbg:/opt/jboss/wildfly/standalone/deployments
    restart: always

  camunda:
    build:
      context: tomcat
      dockerfile: Dockerfile
    image: hicumes.camunda
    logging:
      driver: local
      options:
        max-size: 200m
        max-file: 5
    container_name: camunda
    environment:
      TZ: Europe/Berlin
    volumes:
      - camunda_data:/usr/local/tomcat/camunda-h2-dbs
    ports:
     - 9080:9080
    restart: always
    
  mysql:
    cap_add:
      - SYS_NICE
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: hc_root
      MYSQL_USER: hicumes
      MYSQL_PASSWORD: hc_pwd
      MYSQL_DATABASE: hicumes
      TZ: Europe/Berlin
    volumes:
      - hicumes_mysql:/var/lib/mysql
      
  phpmyadmin:
    depends_on:
        - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
        - '8088:80'
    environment:
      PMA_HOST: mysql

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    command: --import-realm
    restart: always
    ports:
      - '8181:8080'
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      TZ: Europe/Berlin
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    volumes:
      - ./hicumes.realm.json:/opt/keycloak/data/import/hicumes.realm.json
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/theme:/opt/keycloak/themes

  nginx-mft:
    build:
      context: MFT
      dockerfile: Dockerfile
    image: hicumes.mft
    container_name: nginx-mft
    volumes:
      - frontend_data_mft:/usr/share/nginx/html
      - frontend_config_mft:/etc/nginx/conf.d
    command: bash -c "nginx -g 'daemon off;' && nginx -s reload"
    ports:
      - 4200:4200
    environment:
      - NGINX_PORT=4200
      - TZ=Europe/Berlin
    restart: always

  nginx-schema-mapper:
    build:
      context: SchemaMapper
      dockerfile: Dockerfile
    image: hicumes.schmema-mapper
    container_name: nginx-schema-mapper
    volumes:
      - frontend_data_schema_mapper:/usr/share/nginx/html
      - frontend_config_schema_mapper:/etc/nginx/conf.d
    command: bash -c "nginx -g 'daemon off;' && nginx -s reload"
    ports:
      - 4202:4202
    environment:
      - NGINX_PORT=4202
      - TZ=Europe/Berlin
    restart: always

  nginx-feinplanung:
    build:
      context: FPFrontend
      dockerfile: Dockerfile
    image: hicumes.fp_frontend
    container_name: nginx-feinplanung
    volumes:
      - frontend_data_feinplanung:/usr/share/nginx/html
      - frontend_config_feinplanung:/etc/nginx/conf.d
    command: bash -c "nginx -g 'daemon off;' && nginx -s reload"
    ports:
      - 4205:4205
    environment:
      - NGINX_PORT=4205
      - TZ=Europe/Berlin
    restart: always

  hazel-management:
      image: hazelcast/management-center:5.3.2
      ports:
      - "8085:8080"
      environment:
      - MC_DEFAULT_CLUSTER=hicumes_demo
      - MC_DEFAULT_CLUSTER_MEMBERS=hicumes,camunda
      volumes:
      - hazel_management_data:/data

  hicumes-feinplanung:
    build:
      context: feinplanung
      dockerfile: Dockerfile
    image: hicumes.feinplanung
    container_name: feinplanung
    ports: 
      - 5010:5010
    environment:
      Kestrel__Endpoints__Http__Url: "http://0.0.0.0:5010"
      ConnectionStrings__DefaultConnection: "Server=mysql;port=3306;Database=hicumesFP;Uid=hicumes;Pwd=hc_pwd;"

    restart: always

volumes:
  hicumes_mysql:
  frontend_data_mft:
  frontend_config_mft:
  frontend_data_schema_mapper:
  frontend_config_schema_mapper:
  frontend_data_feinplanung:
  frontend_config_feinplanung:
  keycloak_data:
  camunda_data:
  hazel_management_data:  
  keycloak_theme:
